####################################################################################
# Docker-compose file for spinning up a rpc-automagic container
# @author Benjamin Assadsolimani
#
# USAGE: docker-compose up -d
#
####################################################################################

version: '3.2'

services:
  rpc-automagic:
    container_name: rpc-automagic
    build:
      context: .
      dockerfile: Dockerfile
    image: rpc-automagic:latest
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - "127.0.0.1:9126:9229" # Debug port
      - "127.0.0.1:1337:1337" # Default API port
