####################################################################################
# Docker-compose file for spinning up a pm2-rpc-api container
# @author Benjamin Assadsolimani
#
# USAGE: docker-compose up -d
#
####################################################################################

version: '3.2'

services:
  pm2-rpc-api:
    container_name: pm2-rpc-api
    build:
      context: .
      dockerfile: Dockerfile
    image: pm2-rpc-api:latest
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      # Debug port
      - "127.0.0.1:9126:9229"
